server:
  port: 9090
  contextPath: /accountsecurity
spring:
  application:
    name: accountsecurity
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true    
    

